apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order_pub_sub
spec:
# Based on the example from docs, but customized to use the Redis created with 'dapr init' 
  #type: pubsub.rabbitmq
  type: pubsub.redis
  version: v1
  metadata:
  - name: host
    value: localhost:6379 #"amqp://localhost:5672"
  - name: redisPasword
    value: ""
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  #- name: concurrency
    #value: parallel
scopes:
  - orderprocessing
  - checkout

